// Code generated by counterfeiter. DO NOT EDIT.
package vaultfakes

import (
	sync "sync"

	vault "github.com/cappyzawa/cf-push-with-vault/vault"
)

type FakeVariablesFactory struct {
	NewVariablesStub        func() vault.Variables
	newVariablesMutex       sync.RWMutex
	newVariablesArgsForCall []struct {
	}
	newVariablesReturns struct {
		result1 vault.Variables
	}
	newVariablesReturnsOnCall map[int]struct {
		result1 vault.Variables
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeVariablesFactory) NewVariables() vault.Variables {
	fake.newVariablesMutex.Lock()
	ret, specificReturn := fake.newVariablesReturnsOnCall[len(fake.newVariablesArgsForCall)]
	fake.newVariablesArgsForCall = append(fake.newVariablesArgsForCall, struct {
	}{})
	fake.recordInvocation("NewVariables", []interface{}{})
	fake.newVariablesMutex.Unlock()
	if fake.NewVariablesStub != nil {
		return fake.NewVariablesStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.newVariablesReturns
	return fakeReturns.result1
}

func (fake *FakeVariablesFactory) NewVariablesCallCount() int {
	fake.newVariablesMutex.RLock()
	defer fake.newVariablesMutex.RUnlock()
	return len(fake.newVariablesArgsForCall)
}

func (fake *FakeVariablesFactory) NewVariablesCalls(stub func() vault.Variables) {
	fake.newVariablesMutex.Lock()
	defer fake.newVariablesMutex.Unlock()
	fake.NewVariablesStub = stub
}

func (fake *FakeVariablesFactory) NewVariablesReturns(result1 vault.Variables) {
	fake.newVariablesMutex.Lock()
	defer fake.newVariablesMutex.Unlock()
	fake.NewVariablesStub = nil
	fake.newVariablesReturns = struct {
		result1 vault.Variables
	}{result1}
}

func (fake *FakeVariablesFactory) NewVariablesReturnsOnCall(i int, result1 vault.Variables) {
	fake.newVariablesMutex.Lock()
	defer fake.newVariablesMutex.Unlock()
	fake.NewVariablesStub = nil
	if fake.newVariablesReturnsOnCall == nil {
		fake.newVariablesReturnsOnCall = make(map[int]struct {
			result1 vault.Variables
		})
	}
	fake.newVariablesReturnsOnCall[i] = struct {
		result1 vault.Variables
	}{result1}
}

func (fake *FakeVariablesFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.newVariablesMutex.RLock()
	defer fake.newVariablesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeVariablesFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ vault.VariablesFactory = new(FakeVariablesFactory)
